### ISSUE TITLE
decrease the window borders

### ISSUE THREAD

**Issue by YuriFontella** [daniruiz/skeuos-gtk#1]
Is there a way to decrease the borders directly by the theme?
By the settings of xfce not found.

![image](https://user-images.githubusercontent.com/4920619/101058587-0d407400-356c-11eb-9b85-5916b7ab812b.png)

**Comment by daniruiz** [comment]
Sorry, but if I decrease the window border, then resizing the window in xfce becomes really frustrating, as xfwm4 only lets you resize it inside the border.
