### ISSUE TITLE
Trash options not following accent color

### ISSUE THREAD

**Issue by LeFloatyPancake** [daniruiz/skeuos-gtk#14]
I'm not sure if this is intended design or not but should this (trash options) follow the accent color/theme color? I'm using grey-light but its the same color for other light themed variants too.

![options](https://user-images.githubusercontent.com/83509112/122659941-75287600-d1af-11eb-8a19-b44adb6cee7d.png)

**Comment by daniruiz** [comment]
Warnings use that orange color for all themes
