### ISSUE TITLE
[Feature request] Add background color option to generate color theme

### ISSUE THREAD

**Issue by joaopauloalbq** [daniruiz/skeuos-gtk#15]
Hi o/

This theme is awesome! I only found the background color too dark. Could an option be added to modify the color of the background?

Best regards,

**Comment by daniruiz** [comment]
Sorry but that would be super complicated as it would require replacing multiple colors. For the GTK3 theme there's only one color to change as it relies on SASS code, but the other themes use images. Changing the selected color is already very complicated, but changing the background is almost impossible without creating an entire new theme.

**Comment by joaopauloalbq** [comment]
I understand :(
Thanks for the reply
