### ISSUE TITLE
Dark UI elements mixed in light theme

### ISSUE THREAD

**Issue by LeFloatyPancake** [daniruiz/skeuos-gtk#16]
I tested this on Skeuos-blue-light and Skeuos-grey-light and both of them exhibit these conditions. The dark themed elements like the background and the 'undo' button really look unhinged from the rest of the light theme. 

Nautilus 40.2 (if this helps)

![Untitled](https://user-images.githubusercontent.com/83509112/123782831-4d9c8080-d908-11eb-8256-14cabeae9763.png)

**Comment by daniruiz** [comment]
That is indeed intended to make it more visible. That is actually not my personal design, the dark color comes from upstream Adwaita theme.
I'm closing this as it isn't actually an issue, but feel free to reopen it or continue the discussion if you feel so.
