### ISSUE TITLE
Gnome Shell Theme (and gresource.xml to compile)

### ISSUE THREAD

**Issue by quebin31** [daniruiz/skeuos-gtk#2]
It would be great to have a Gnome Shell Theme out of this theme, and also a `gresource.xml` file to compile into glib resources and override default shell theme.

**Comment by Tomoghno** [comment]
@daniruiz should consider to add GNOME Shell
Theme and a GDM Theme.

**Comment by daniruiz** [comment]
The shell theme is Flat-Remix-Gnome
