### ISSUE TITLE
Flatpak build 

### ISSUE THREAD

**Issue by mbousq** [daniruiz/skeuos-gtk#27]
Hi ! Excellent theme, thank you very much. If you have time would it be possible make a flatpak version to have a unified experience ?

Regards

**Comment by daniruiz** [comment]
I don't have the time to support flatpak, and to me it makes more sense to run one setting instead of having to install 2 different themes from different packages

Run: `flatpak override --filesystem=~/.themes/`
and you'll be able to use the themes
