### ISSUE TITLE
Open, Save, and Save All buttons seem ambiguous (up is open, down is save)

### ISSUE THREAD

**Issue by poikilos** [daniruiz/skeuos-gtk#31]
I'm not sure if Skeuos is based on Flat Dark Remix or whether that is based on Skeuos. Both look the same except Flat Dark Remix requires Flat Dark Metacity, but Skeuos includes it and works fine. Both themes have an up and down arrow for open and save. The buttons aren't intuitive. I understand the symbolism of down going down to the drive or something, but in a world of web applications the buttons are counter-intuitive (and I recently almost overwrote an important file):
- Open being an up arrow is unexpected because :arrow_up:  can mean upload, but you are "downloading" in a symbolic way.
- Save and Save All being a down arrow and down arrow with "A" over it are unexpected because :arrow_down:  can mean downlod, but you are "uploading" in a symbolic way.

I tried:
- to read documentation and unofficial documentation of creating GTK themes
- search for "open" "save" "load" and "arrow.up" and "arrow.down" in the css files of the theme, but I can't figure out how to change the icons.
- visually look at every icon included in the theme

Suggestions:
- Clarify whether this is a fork of [Flat Remix GNOME/Ubuntu/GDM](https://www.gnome-look.org/p/1013030) or the other way around or neither.
- If you agree, make the change in the repo to the 3 icons, otherwise please help me change the icons.

**Comment by daniruiz** [comment]
What arrows are you talking about? Can you send a screenshot?

The new version of Flat-Remix-GTK (not the gnome one) Is based on Skeuos code, as it was easier to maintain.
The metacity themes are sepparated differently because there are only Light, Dark and Darkest variants for Flat-Remix, while Skeuos changes the color of the window buttons for each variant, thus it has one variant for each GTK theme. This way it reduces duplicated metacity themes for Flat-Remix

**Comment by poikilos** [comment]
Thanks for the info. Here are the up and down arrows in Geany:
![image](https://user-images.githubusercontent.com/7557867/144611854-3fd18041-868a-45ca-a162-967e0a0872c0.png)

**Comment by daniruiz** [comment]
You mean the Icon theme, not the GTK theme.
The icons are correct, even the originals had the down arrow. The up arrow icons mean import from disk into the program (which works on a higher lever, if you want to see a metaphor) 

![image](https://user-images.githubusercontent.com/12565871/144636932-062de7e0-01e9-4baf-9d13-c09817f286c6.png)
