### ISSUE TITLE
Icons for plus and minus symbols are missing such as in git-cola

### ISSUE THREAD

**Issue by poikilos** [daniruiz/skeuos-gtk#32]
Here's how it looks (There is no + or - symbol even though you can click there, after the closed :book: icon):
![image](https://user-images.githubusercontent.com/7557867/144613013-775aeec5-fe70-41de-9df2-63ad444c3e6c.png)

Here's how it should look (Skeuos Black Light is used in the screenshot, but Skeuos Grey Light is also unaffected):
![image](https://user-images.githubusercontent.com/7557867/144613977-8ef87470-bb0d-431f-a2c5-719ee5c5012f.png)

After applying the theme, you have to restart git-cola to see results.

**Comment by daniruiz** [comment]
You need to use the icon theme Flat-Remix-Light.
This is the repository of the Skeuos GTK theme, not the icon theme. And that's a QT app so the GTK theme has nothing to do
