### ISSUE TITLE
Add it to the flathub repo?

### ISSUE THREAD

**Issue by tio-trom** [daniruiz/skeuos-gtk#38]
I wanted to ask you if you plan to add it to the flathub repository so that it can be used by the now-popular flatpaks? Thanks!

**Comment by daniruiz** [comment]
I don't have the time to support flatpak, and to me it makes more sense to run one setting instead of having to install 2 different themes from different packages

Run: flatpak override --filesystem=~/.themes/
and you'll be able to use the themes

**Comment by tio-trom** [comment]
Yes I agree it doesn't make much sense the way flatpak deals with the themes....I thought it was not a big deal to make a flatpak theme but if it is forget about it. Thank you for your work!
