### ISSUE TITLE
Highlight desktop icons transparency

### ISSUE THREAD

**Issue by GyoMan** [daniruiz/skeuos-gtk#40]
![image](https://user-images.githubusercontent.com/16439531/171177968-22323aff-fdfb-465e-aaca-0267b3f4adf8.png)

There's no transparency while selecting with the rubberband items on the desktop (works ok when selecting items in a window)

Tried all different color options.

Linux Mint Xfce 20.3

**Comment by daniruiz** [comment]
This is fixed now ;)
Thanks for reporting! <3
