### ISSUE TITLE
Some issues in Gnome 

### ISSUE THREAD

**Issue by KristianUSN** [daniruiz/skeuos-gtk#5]
Fantastic theme, but on Gnome I've discovered a few issues:
- In the Foliate application the "Library" button will stretch outside of window borders (but switching workspace back and forth will fix it and make it look normal for some reason)
- In the updated Geary application, some buttons will have same height as title/toolbar which looks really out of place
- Expanded close button will "clip" in Firefox
 
Some screenshots of each respective issue:

![Screenshot-20210505221859-2166x174](https://user-images.githubusercontent.com/46893137/117204645-dd361f00-adf0-11eb-92ba-23f674b7f417.png)
![Screenshot-20210505221922-1532x176](https://user-images.githubusercontent.com/46893137/117204660-e32c0000-adf0-11eb-9a05-f9b7519394af.png)
![image](https://user-images.githubusercontent.com/46893137/117204722-fb038400-adf0-11eb-951b-90bbf4e3a575.png)

**Comment by daniruiz** [comment]
* Fixed the titlebuttons for firefox
* The issue with geary is weird, because they don't work neither with Adwaita, but if you install it from flatpak they work perfectly even with my theme. (tested on arch)

**Comment by daniruiz** [comment]
The issue with geary is now fixed for Arch, so that's not an issue of the theme. And I can't fix the one from foliate so I'm closing this issue
