### ISSUE TITLE
Problem with firefox in cinnamon

### ISSUE THREAD

**Issue by daddy33** [daniruiz/skeuos-gtk#6]
Hello,

when firefox is configured to remove the titlebar and you maximize window (cinnamon), there is a thick black border above that can't be removed.
![Capture d’écran du 2021-05-27 11-58-39](https://user-images.githubusercontent.com/9918544/119807232-3faba800-bee3-11eb-97d9-08cc63727b3b.png)
Thanks. Great theme.

**Comment by daniruiz** [comment]
It only happens with firefox?
Does it happen with other themes?

**Comment by daddy33** [comment]
Yes, only firefox. But a few other themes are affected : vertex, marwaita, maybe flat-remix although I am not sure.

**Comment by mseveritt** [comment]
This issue should be resolved with Firefox 96: https://bugzilla.mozilla.org/show_bug.cgi?id=1746486
