### ISSUE TITLE
Makefile exits with error code 2

### ISSUE THREAD

**Issue by bridnour** [daniruiz/skeuos-gtk#7]
I downloaded the source data for skeuos-gtk to create a custom color.  Unfortunately, the makefile exits with a error code (#2).

It does the same thing if I try to make the standard color set.

I've attached the output of both builds.
[build.log](https://github.com/daniruiz/skeuos-gtk/files/6576347/build.log)
[dracula.log](https://github.com/daniruiz/skeuos-gtk/files/6576348/dracula.log)

**Comment by bridnour** [comment]
It looks like the error is here:
src/assets-renderer/metacity/

The links for assets.svg and assets-dark.svg need to be updated.

**Comment by daniruiz** [comment]
Thank you!
I didn't notice I broke that symlinks ;)
